version: '3.4'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: prod
        image: "ldi/dom_exp:0.1"
        container_name: "dom_exp_app"
        restart: always
        env_file:
            - .env
        ports:
            - 9001:9000
